### ISSUE TITLE
Én, mint user, ha szöveg címe alapján keresek, akkor szeretném megkapni, az adott szöveget.

### ISSUE THREAD

**Issue by Forestal75** [shaolinMasters/akkadian-lexicon#10]
1. Scenario: Szöveg cime alapjan valo kereses

Given: a user elnavigal a kereses menube
And: kivalasztja, hogy szovegcim alapjan keres

Then: egy megjeleno listabol kivalaszthatja, az adott forrást, szoveget

Given: kivalasztott egyet

Then: a kiválasztott forrás szövege megjelenik

**Comment by marinchuck** [comment]
done
