### ISSUE TITLE
Login oldal letrehozasa

### ISSUE THREAD

**Issue by marinchuck** [shaolinMasters/akkadian-lexicon#45]

**Comment by balazscsorgo** [comment]
miutan bejelentkezett (rakattintott a login gombra) az admin megjelenik egy edit gomb. az edit oldalon hasonlo radio gombokkal lehet lehet valasztani, hogy kiralyt, forrast vagy szot szeretne szekeszteni, a kivalasztas utan ket kategoria kozul lehet valasztni (torles es hozzaadas).
